### ISSUE TITLE
parse-resque only runs the first job in the queue and it fails with following message.

### ISSUE THREAD

**Issue by stryk** [gfosco/parse-resque#2]
'TypeError: Cannot call method 'then' of undefined at parse-rita.js:126:43 at e (Parse.js:2:6486) at Parse.js:2:5935 at Array.forEach (native) at Object.x.each.x.forEach [as _arrayEach](Parse.js:1:664) at c.extend.resolve (Parse.js:2:5886) at Parse.js:2:6565 at e (Parse.js:2:6486) at Parse.js:2:5935 at Array.forEach (native)'

Only thing I did was to rename an entry in module export from addJob to job as someone pointed out.
When I investigated this, the jobs do get queued up in the database, it's just that only one job is executed then the worker fails out.  I'm on parse version 1.3.2

Thanks

**Comment by gfosco** [comment]
Oh.. Hmm, I have not looked at this in a while.  I'll take a look and try to update this (but I may want to make some larger changes.)
